services:
  db:
    image: mariadb:10.9
    container_name: ${BRANCH_NAME}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 10

  web:
    image: lsuonline/moodle-dev:latest
    container_name: ${BRANCH_NAME}-moodle
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: moodle
      DB_USER: moodleuser
      DB_PASSWORD: moodlepass
      BRANCH_NAME: ${BRANCH_NAME:-default}
    restart: always
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${BRANCH_NAME}-moodle.rule=Host(`moodle.${BRANCH_NAME}.localhost`)
      - traefik.http.routers.${BRANCH_NAME}-moodle.entrypoints=web
      - traefik.http.services.${BRANCH_NAME}-moodle.loadbalancer.server.port=80
      - traefik.docker.network=traefik

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${BRANCH_NAME}-phpmyadmin
    depends_on:
      - db
    networks:
      - default
      - traefik
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${BRANCH_NAME}-phpmyadmin.rule=Host(`phpmyadmin.${BRANCH_NAME}.localhost`)
      - traefik.http.routers.${BRANCH_NAME}-phpmyadmin.entrypoints=web
      - traefik.http.services.${BRANCH_NAME}-phpmyadmin.loadbalancer.server.port=80
      - traefik.docker.network=traefik

  workday-simulator:
    image: lsuonline/workday-simulator
    container_name: ${BRANCH_NAME}-workday-simulator
    environment:
      SEED_DATA: "true"
      SEED_STUDENTS: 1000
      SEED_EMPLOYEES: 100
      SEED_COURSES: 50
      SEED_SECTIONS: 150
      AUTH_PASSWORD_ACADEMIC: academic
      AUTH_PASSWORD_EMPLOYEE: employee
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${BRANCH_NAME}-workday-simulator.rule=Host(`workday-simulator.${BRANCH_NAME}.localhost`)
      - traefik.http.routers.${BRANCH_NAME}-workday-simulator.entrypoints=web
      - traefik.http.services.${BRANCH_NAME}-workday-simulator.loadbalancer.server.port=8080
      - traefik.docker.network=traefik
    restart: always

networks:
  traefik:
    external: true