version: "3.8"

services:

  db:
    image: mariadb:10.9
    container_name: moodle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    # volumes:
    #   - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle_web
    depends_on:
      - db
    ports:
      - "8080:80"
    # volumes:
    #   - "./lsuce-moodle:/var/www/html"
    environment:
      DB_HOST: db
      DB_NAME: moodle
      DB_USER: moodleuser
      DB_PASSWORD: moodlepass
    restart: always